controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    fireball = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 5 5 5 4 4 . . . . . . . 
        . . . 5 5 4 4 2 4 4 . . . . . . 
        . . 5 5 5 4 2 2 2 4 . . . . . . 
        . . . . 5 4 4 2 2 4 . . . . . . 
        . . . . 5 5 4 4 4 4 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, Starship_Z, 200, 0)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.fire, 500)
    sprite.destroy()
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy()
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
let bogey: Sprite = null
let fireball: Sprite = null
let Starship_Z: Sprite = null
Starship_Z = sprites.create(img`
    ..............fffcc.................
    ..............fbbddc................
    ...............fbbddc...............
    ccc............fcbbccf..............
    cbbcc.........ffccccccffffff........
    .cbbdc.....fffcbbbbbbbbbbbbbff......
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff....
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf....
    ..fcbbbcccccccbbbcbcb1ff1111bbbf....
    ..fccbcccccccccbbbbbb11111111bf.....
    .fcbbfffccccccccbbbb11cc33cccf......
    .fbbf...cbdbcccccbbb111c131cf.......
    fbbf.....ccdddddfbbbc111c33f........
    fff........ccddfbbdbf1111ff.........
    .............cfbbdbfccccc...........
    ..............fffff.................
    `, SpriteKind.Player)
controller.moveSprite(Starship_Z, 200, 200)
Starship_Z.setStayInScreen(true)
info.setLife(3)
game.onUpdateInterval(500, function () {
    bogey = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111df.......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd1dfbddddbf......
        ......fbddfcdbbbcf......
        .......f11111bbcf.......
        .......f1b1fffff........
        .......fbfc111bf........
        ........ff1b1bff........
        .........fbfbfff.f......
        ..........ffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    bogey.setVelocity(-100, 0)
    bogey.setPosition(160, randint(5, 115))
    bogey.setFlag(SpriteFlag.AutoDestroy, true)
})
